### ISSUE TITLE
how to carry out multi-GPU with lightning-pose?

### ISSUE THREAD

**Issue by Wulin-Tan** [paninski-lab/lightning-pose#138]
Hi, lighting pose team
I am very interested in this super cool tool.
How to do multi-GPU with lighting pose?
I can't find multi-GPU information in the tutorial.

**Comment by themattinthehatt** [comment]
We do not currently support multi-GPU training but it should not be difficult to implement with our current setup (at least for the supervised models). We'll be happy to look into this but it might take us a week or so, we'll keep you updated.

**Comment by YitingChang** [comment]
I'm also interested in multi-GPU training and would like to follow this. Thank you!

**Comment by YitingChang** [comment]
Hi @ksikka , 

Thank you for following up! I'm encountering memory limitations with a single GPU, so I'd like to explore running Lightning Pose with multiple GPUs.

To give you more context on my current setup: as I add more features—such as unsupervised losses and temporal context networks—the memory demands increase. I've had to significantly resize images and reduce batch sizes to fit within the memory constraints. Currently, I’m running Lightning Pose on a cluster with one GPU that has 40 GB of memory. Allocating more GPUs shouldn't be an issue if Lightning Pose can support multi-GPU functionality.

**Comment by Wulin-Tan** [comment]
@ksikka yes, I need to handle more GPU memory as well as faster training if possible.

**Comment by ksikka** [comment]
Hi @YitingChang and @Wulin-Tan support for multi-GPU was just added for supervised training. This works for both heatmap and heatmap_mchrnn as long as `losses_to_use: []`. Support for multi-gpu when using unsupervised losses is in the works.

**Comment by ksikka** [comment]
Without multi-gpu on unsupervised, you might have success with gradient accumulation (see `accumulate_grad_batches` in the [configuration file docs](https://lightning-pose.readthedocs.io/en/latest/source/user_guide/config_file.html). Say you want an effective batch size of 8 but can only fit batch size 2 in memory. then you could set `train_batch_size: 2` and `accumulate_grad_batches: 4`. This is an experimental feature so if you do try it, report back with your feedback. Thanks!

**Comment by ksikka** [comment]
Hi @YitingChang and @Wulin-Tan support for multi-GPU was just added for unsupervised training and is now ready for you to try out! We've tested it and been pleased with the results. Please see the guide here, and report back if it has helped you.
https://lightning-pose.readthedocs.io/en/latest/source/user_guide_advanced/multi_gpu_training.html

**Comment by YitingChang** [comment]
Awesome! I'll try it next week and report back.

**Comment by YitingChang** [comment]
Hi @ksikka I was trying to run multi-GPU training on a cluster node with 4 NVIDIA a100 GPUs and 48 CPUs. However, I got the following error. It seems that Lightning didn't recognize the 4 GPUs correctly. Is there any parameters in the configuration file that I can change? Thank you!

[/opt/dali/dali/operators/image/crop/new_crop_mirror_normalize.cu:249] using CropMirrorNormalize legacy implementation
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Error executing job with overrides: []
Traceback (most recent call last):
  File "/vast/doconn15/projects/hand_tracking/lightning-pose-gpu/scripts/train_hydra.py", line 35, in train_model
    train(cfg)
  File "/home/ychang73/.conda/envs/litpose-gpu/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/vast/doconn15/projects/hand_tracking/lightning-pose-gpu/lightning_pose/train.py", line 131, in train
    trainer.fit(model=model, datamodule=data_module)
  File "/home/ychang73/.conda/envs/litpose-gpu/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/home/ychang73/.conda/envs/litpose-gpu/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 46, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/ychang73/.conda/envs/litpose-gpu/lib/python3.10/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 99, in launch
    self.cluster_environment.validate_settings(num_devices=self.num_processes, num_nodes=self.num_nodes)
  File "/home/ychang73/.conda/envs/litpose-gpu/lib/python3.10/site-packages/lightning/fabric/plugins/environments/slurm.py", line 163, in validate_settings
    raise ValueError(
ValueError: You set `devices=4` in Lightning, but the number of tasks per node configured in SLURM `--ntasks-per-node=48` does not match. HINT: Set `devices=48`.

**Comment by ksikka** [comment]
The lightning framework we use is auto-detecting SLURM, we haven't tested with SLURM before.

The first to try is to unset some SLURM environment variables when running train hydra (got this idea from [here](https://github.com/Lightning-AI/pytorch-lightning/issues/5225#issuecomment-750032030))

```
# Creates a subshell using parentheses () to isolate the environment modifications.
(unset SLURM_NTASKS SLURM_JOB_NAME; python scripts/train_hydra.py)
```

Can you also share how you enqueued the job? Maybe there is a way to change `--ntasks-per-node=48` to `--ntasks-per-node=4`? Will help me understand what's going on here.

**Comment by YitingChang** [comment]
My SLURM script:

#!/bin/bash -l
#SBATCH --job-name=hand-1cam_namd4gpu
#SBATCH --time=2:00:00
#SBATCH --partition=a100
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=48 
#SBATCH --gres=gpu:4
#SBATCH -A xxx ### Slurm-account
#SBATCH --error=err.txt
#SBATCH --output=myLog-file.txt
#SBATCH --export=ALL

###Load modules and check
source /data/apps/helpers/Lmod
ml restore
module load namd/2.14-cuda-smp
module load anaconda
ml

# Set GPUs to be visible
available_devs=""

for devidx in $(seq 0 15);

do

        if [[ -z $(nvidia-smi -i $devidx --query-compute-apps=pid --format=csv,noheader) ]] ; then

             if [[ -z "$available_devs" ]] ; then

                  available_devs=$devidx

             else  

                 available_devs=$available_devs,$devidx

             fi

         fi

done

export CUDA_VISIBLE_DEVICES=$available_devs
export CONV_RSH=ssh

###Activate the virtual environment
conda activate /home/ychang73/.conda/envs/litpose-gpu

###Run the python script
python scripts/train_hydra.py --config-path=/vast/doconn15/projects/hand_tracking/lightning-pose-gpu/data/LP_240726 --config-name=config_hand-1cam-4gpu.yaml

###Deactivate the virtual environment
conda deactivate

**Comment by ksikka** [comment]
Thanks, 

I would try changing --ntasks-per-node to 4. 

Feel free to message on discord where we can go back and forth more quickly.

**Comment by ksikka** [comment]
And run the python command with `srun`. I'm using https://lightning.ai/docs/pytorch/stable/clouds/cluster_advanced.html#run-on-a-slurm-managed-cluster for inspiration.
