### ISSUE TITLE
Running on Mac OS

### ISSUE THREAD

**Issue by ytsimon2004** [paninski-lab/lightning-pose#190]
Hello, Thanks for the great tool,
I wonder if the developers managed to make it compatible with Mac OS, (i.e., using `MPS` backend)?

**Comment by themattinthehatt** [comment]
@ytsimon2004 thanks for the question - we still have not made any attempts to make lightning pose compatible with Mac OS. The limiting factor so far is DALI, which is not supported on macs: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/FAQ.html#q-which-os-does-dali-support

I'm not familiar with the `MPS` backend, so maybe that's a way forward?
